# Autogenerated wrapper script for CUDA_SDK_jll for aarch64-linux-gnu-cuda_platform+sbsa
JLLWrappers.@generate_wrapper_header("CUDA_SDK")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
